### ISSUE TITLE
Show a thumbnail if youtube cannot be reached

### ISSUE THREAD

**Issue by ghoshbishakh** [nipy/dipy_web#11]
In some countries youtube is blocked. Display a thumbnail instead of the broken iframe in that case.

**Comment by jchoude** [comment]
I honestly don't think we should bother supporting that. As you said, if youtube is blocked, fetching the thumbnail will also fail.

I believe that, if a user is technically advanced enough to use / develop on Dipy, he will be able to bypass Youtube blocking.
