### ISSUE TITLE
Critical error 404 on contributors

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy_web#21]
Yesterday I could see this page
http://dipy.herokuapp.com/contributors/
Today I cannot. I am getting an 404 error.

**Comment by ghoshbishakh** [comment]
@Garyfallidis Found the problem. But this looks like some fault from github API.

As you can see in this url:

https://api.github.com/repos/nipy/dipy/stats/contributors

It returns a list of contributors and their weekly contribution statistics.

Somehow it is returning a `"author": null` now. And that null person has total 17 contributions! So from github I found that the person that should have been listed as author here is probably wenderen

**Comment by ghoshbishakh** [comment]
@Garyfallidis I don't know how is this possible. I will try contacting github support once.

**Comment by ghoshbishakh** [comment]
In case the output from GitHub API changes in future here is the dump:
https://gist.github.com/ghoshbishakh/0d9dd375f907af73b6c989af47c6e0b5

**Comment by ghoshbishakh** [comment]
Got a reply from GitHub:

> Thanks for reaching out and asking about this! The behavior you have observed is expected for now. Below, I've outlined some information that clarifies what's happening here.

> The data that's shown in this endpoint:

> https://developer.github.com/v3/repos/statistics/#get-contributors-list-with-additions-deletions-and-commit-counts

> is the same data that's shown whenever you look at a repository's contributors graphs:

 >   https://github.com/:user/:repo/graphs/contributors

> You said that when you made a request to https://api.github.com/repos/nipy/dipy/stats/contributors, there is a "author": null entry and that author has total 17 contributions.

> When I look at this repository's contributor's graph:

> https://github.com/nipy/dipy/graphs/contributors

> I see that wenderen contributed exactly 17 commits to this repository. When I click the user profile, I'm led to a 404 Page:

> https://github.com/wenderen

> This help article goes over the criteria for how a commit is counted as a contribution:

> https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commits

> One of the four conditions for having a commit count as a contribution to the repository is if the email address used for that commit is associated with a specific GitHub account. In this case, it's possible that this user may have renamed or deleted their GitHub account which would break the link between their username and the email address associated with those commits, thereby invalidating their contributions to this repository and rendering a null value for the author.

> I can see how this can be confusing, so I've opened up an internal issue so the team can see. I can't promise if this behavior will change in the future, but if you have any other thoughts about it, you're welcome to write back.

> I hope that helps, but let us know if you have any other questions!

The problem is some contributer deleted or renamed the profile and the API was returning null. And after sometime the entry for that user is removed entirely.

So we need to handle the error for that intermediate period.

I am going to ignore the contributor if its info is returned as null.
