### ISSUE TITLE
Github data is not fetched in heroku properly

### ISSUE THREAD

**Issue by ghoshbishakh** [nipy/dipy_web#27]
Sometimes the github data is fetched partially or not fetched atall in heroku. However it is working fine locally.

**Comment by Garyfallidis** [comment]
The issues seems worsened now. We can not even see the contributors.
http://dipy.herokuapp.com/contributors/

**Comment by ghoshbishakh** [comment]
@Garyfallidis Yes and sometimes django is caching the partial data. I will try to make a check and put some retry loops in the fetching process and throw an error if it fails to fetch.

**Comment by Garyfallidis** [comment]
Now seems working.

**Comment by jchoude** [comment]
Also do not forget that, as soon as we find a more reliable host, this issue might be mitigated.

**Comment by ghoshbishakh** [comment]
Yes that is why I am hesitating to change anything as it is working in
local host without any problems

**Comment by Garyfallidis** [comment]
ok

**Comment by ghoshbishakh** [comment]
@Garyfallidis looks like it is fixed. http://elef.soic.indiana.edu/contributors/

**Comment by skoudoro** [comment]
closing, seems to be fixed
