### ISSUE TITLE
Consider using a fixed width font in code snippets

### ISSUE THREAD

**Issue by arokem** [nipy/dipy_web#29]
I think it helps make the code more readable.

**Comment by ghoshbishakh** [comment]
@arokem by fixed width font do you mean monospace fonts or the container of the code needs a fixed width?

**Comment by arokem** [comment]
Monospace font

**Comment by ghoshbishakh** [comment]
@arokem I have deployed the change in heroku 
http://dipy.herokuapp.com/

**Comment by ghoshbishakh** [comment]
sorry for the delay I have my mid semester exams coming, I will try to finish the changes gradually after that.
