### ISSUE TITLE
Gallery and tutorials do not work

### ISSUE THREAD

**Issue by Garyfallidis** [nipy/dipy_web#40]
http://elef.soic.indiana.edu/gallery/

**Comment by ghoshbishakh** [comment]
No Idea what caused this issue. Looking into it

**Comment by skoudoro** [comment]
ping @ghoshbishakh. Any ideas ?

**Comment by ghoshbishakh** [comment]
@skoudoro I have not yet got the actual issue.

**Comment by skoudoro** [comment]
Apache server was blocking all inline script because of CSP  header. 

It works now so I close this issue
