### ISSUE TITLE
[QUESTION] CSS, SCSS

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy_web#42]
I wonder how can i change css/scss to play a little bit with the website. Can you describe the process for modifying or adding any design ? 

it seems css is generated by scss but how ? any advise @ghoshbishakh ?

**Comment by ghoshbishakh** [comment]
Just compile the [main.scss](https://github.com/nipy/dipy_web/blob/master/website/static/css/main.scss) into main.css
Use any scss compiler. http://sass-lang.com/install

And scss is compatible with CSS so your CSS code will work fine. It just adds some extra features.

**Comment by skoudoro** [comment]
Thanks ! I can play with them now. Closing
