### ISSUE TITLE
Slow function :  get_doc_examples()

### ISSUE THREAD

**Issue by skoudoro** [nipy/dipy_web#44]
`get_doc_examples` in `website/views/tool.py` is too slow. Duration of this function :  **7.704431056976318 secondes**

We should improve this function even if the cache helps us after all.

**Comment by skoudoro** [comment]
Maybe we should [let BeautifulSoup and use lxml parser](https://www.crummy.com/software/BeautifulSoup/bs4/doc/#specifying-the-parser-to-use)

lxml seems to be really faster.

**Comment by ghoshbishakh** [comment]
@skoudoro and with lxml how long is it taking?

**Comment by skoudoro** [comment]
By using `BeautifulSoup(response_json['body'], "lxml")` for a quick test, it takes: **4.077622652053833 secondes**

So, I think we can improve it by using lxml only.

**Comment by ghoshbishakh** [comment]
@skoudoro great! So I guess you have already figured out how different parses are working. Have you checked #40 ?

**Comment by skoudoro** [comment]
Since it works locally, not yet.

Do you know where is the logger ?

when I go to `apachelogs/error.log`  on the server, I see : 

`[autoindex:error] [pid 3995] [client ] AH01276: Cannot serve directory /u/dipy/dipy_web/dipy_web/staticfiles/js/: No matching DirectoryIndex (index.html,index.php) found, and server-generated directory index forbidden by Options directive`

I do not know yet what that means

**Comment by ghoshbishakh** [comment]
so this path exists or not? `u/dipy/dipy_web/dipy_web/staticfiles/js/`

**Comment by skoudoro** [comment]
workaround has been applied here so closing
