### ISSUE TITLE
Gallery suggestions

### ISSUE THREAD

**Issue by arokem** [nipy/dipy_web#47]
The gallery is a bit overwhelming and you can't see what each example is until you hover over the particular hexagon (only then does the text appear). 

Suggestions: 

1. Divide the page into sub-sections. 
2. Show the titles (or at least a keyword) in each hexagon. 
(3. Alternatively: provide an examples index somewhere).

**Comment by skoudoro** [comment]
Like the tutorial page? https://elef.soic.indiana.edu/tutorials

**Comment by arokem** [comment]
Ah yes. That's perfect.
